tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up
ports:
  - port: 8080
    onOpen: ignore
  - port: 3000
    onOpen: open-browser
 
vscode:
  extensions:
    - vscjava.vscode-java-pack